"""
Main Snakefile for strain-focused pipeline that assembles MAGs from long-read ONT metagenomic data.

Run with, e.g.:
    snakemake --configfile config/config.yaml --config samples_sheet=samples.tsv outdir=pipeline-out \
        --use-conda --cores 16
"""

configfile: "config/config.yaml"

OUTDIR = config["outdir"]

include: "rules/common.smk"

SAMPLES_FASTQ, SAMPLES_POD5 = load_samples(config["samples_sheet"])
SAMPLES = list(SAMPLES_FASTQ) + list(SAMPLES_POD5)

ASSEMBLERS = config.get("assemblers", ["metaflye"])
for _a in ASSEMBLERS:
    if _a not in ("metaflye", "nanomdbg", "myloasm"):
        raise ValueError(f"Unknown assembler {_a!r} in assemblers; expected metaflye, nanomdbg, or myloasm")

include: "rules/basecalling.smk"
include: "rules/qc.smk"
include: "rules/assembly.smk"
include: "rules/strainphasing.smk"
include: "rules/polishing.smk"
include: "rules/binning.smk"
include: "rules/refinement.smk"
include: "rules/binqc.smk"
include: "rules/taxonomy.smk"

## Rules and targets for running stages one-by-one

def qc_targets():
    targets = []
    for sample in SAMPLES:
        targets.append(f"{OUTDIR}/00-QC/{sample}/nanoplot_raw")
        targets.append(f"{OUTDIR}/00-QC/{sample}/nanoplot_filtered")
    return targets


def assembly_targets():
    return [
        f"{OUTDIR}/01-LongAssemblies/{sample}/{assembler}/assembly.fasta"
        for sample in SAMPLES
        for assembler in ASSEMBLERS
    ]


def polishing_targets():
    return [
        f"{OUTDIR}/02-Polishing/{sample}/{assembler}/polished_assembly.fasta"
        for sample in SAMPLES
        for assembler in ASSEMBLERS
    ]


def binning_targets():
    targets = []
    for sample in SAMPLES:
        for assembler in ASSEMBLERS:
            targets.append(f"{OUTDIR}/03-LongBins/{sample}/{assembler}/INITIAL_BINNING/metabat2/metabat2-bins")
            targets.append(
                f"{OUTDIR}/03-LongBins/{sample}/{assembler}/INITIAL_BINNING/semibin/semibin-output/output_bins"
            )
            if cfg_bool("use_comebin"):
                targets.append(f"{OUTDIR}/03-LongBins/{sample}/{assembler}/INITIAL_BINNING/comebin/comebin-bins")
    return targets


def refinement_targets():
    return [
        f"{OUTDIR}/03-LongBins/{sample}/{assembler}/BIN_REFINEMENT/refined-bins"
        for sample in SAMPLES
        for assembler in ASSEMBLERS
    ]


def binqc_targets():
    targets = []
    for sample in SAMPLES:
        for assembler in ASSEMBLERS:
            targets.append(f"{OUTDIR}/04-BinQC/{sample}/{assembler}/staging/checkm2-result/quality_report.tsv")
            targets.append(f"{OUTDIR}/04-BinQC/{sample}/{assembler}/staging/gunc-result")
            targets.append(f"{OUTDIR}/04-BinQC/{sample}/{assembler}/staging/passed_bins.list")
            for bin_id in get_bin_ids({"sample": sample, "assembler": assembler}):
                targets.append(
                    f"{OUTDIR}/04-BinQC/{sample}/{assembler}/staging/polished-bins/{bin_id}.rrna.gff"
                )
                targets.append(
                    f"{OUTDIR}/04-BinQC/{sample}/{assembler}/staging/polished-bins/{bin_id}.trna.txt"
                )
    return targets


def taxonomy_targets():
    return [
        f"{OUTDIR}/{sample}.{assembler}.pipeline.ont.genome.summary"
        for sample in SAMPLES
        for assembler in ASSEMBLERS
    ]


def strainphasing_targets():
    return [
        f"{OUTDIR}/06-StrainPhasing/{sample}/{assembler}/strainy-result"
        for sample in SAMPLES
        for assembler in ASSEMBLERS
    ]


def all_targets():
    targets = qc_targets() + taxonomy_targets()
    for sample in SAMPLES:
        for assembler in ASSEMBLERS:
            targets.append(f"{OUTDIR}/04-BinQC/{sample}/{assembler}/staging/gunc-result")
    if cfg_bool("run_strain_phasing"):
        targets += strainphasing_targets()
    if "myloasm" in ASSEMBLERS:
        targets += [f"{OUTDIR}/06-StrainPhasing/{sample}/myloasm/alternate-contigs.fa" for sample in SAMPLES]
    return targets


rule all:
    input:
        all_targets(),


rule qc:
    input:
        qc_targets(),


rule assembly:
    input:
        assembly_targets(),


rule polishing:
    input:
        polishing_targets(),


rule binning:
    input:
        binning_targets(),


rule refinement:
    input:
        refinement_targets(),


rule binqc:
    input:
        lambda wc: binqc_targets(),


rule taxonomy:
    input:
        taxonomy_targets(),


if cfg_bool("run_strain_phasing"):

    rule strainphasing:
        input:
            strainphasing_targets(),
